### PR TITLE
Only add cookie-session if req.session doesn't already exist

### LINKED ISSUE #12: Unable to use Flexdash when adminAuth configured for OAuth
When `adminAuth` is configured for oauth access, opening the flexdash page results in a fatal error:

```
TypeError: req.session.touch is not a function
```

I have tracked down the root cause and will be raising a PR shortly with a proposed fix/workaround in Flexdash.

In summary, with adminAuth setup, Node-RED sets `req.session` to an instance of `express-session`. This includes a hook once the request is completed to trigger a refresh of the cookie (by calling `req.session.touch()`).

Flexdash uses `cookie-session` (https://github.com/flexdash/node-red-flexdash/blob/main/flexdash-dashboard.js#L278)

This sets `req.session` to a new session object with every request that hits the flexdash express app. In doing so it overwrites the existing `req.session` value with a different session implementation that doesn't include `touch`. So when `express-session` runs its code to refresh the cookie, `req.session` is no longer the one it expected and you get the reported error.

There are a number of long-open issues around supporting multiple session objects in express to help support this type of application co-existence - unfortunately they have not got anywhere with proposed PRs unmerged.

Having explored various options in both Node-RED and flexdash, I think the only practical solution is to add some conditional logic around where flexdash sets up `req.session` to only do so if no such object already exists. I have verified that works locally for the simple case of accessing the dashboard, but not done an exhaustive test of flexdash's cookie handling to ensure it all hangs together as expected.

_Originally reported here: https://github.com/flowforge/flowforge/issues/1778_

### PR DESCRIPTION
**Pull request by knolleary**
Fixes #12

One piece I'm not sure on is the socket.io handling - I can see you use some tricks to add headers to the websocket request. In my local testing I *think* that was okay to leave as-is, but would appreciate your input as you've clearly been down that path before.

### CODE REVIEW

**Comment by knolleary** [comment]
Hey @tve - are you able to look at this PR? The issue is prevent anyone with `adminAuth` setup on their Node-RED from using FlexDash - would be great to unblock that.

**Comment by tve** [comment]
Thanks for the nudge! I had taken a look at the changes and couldn't tell the impact. FlexDash in general doesn't require a cookie,  but as soon as the flows need to track users in any way for auth or preferences a cookie is needed. The PR removes the cookie set by FD, which means that this functionality will break as far as I can tell. If FD can't set a cookie then it would need to rely on a cookie set by FF and I don't know whether that's the case and how to hook the cookie ID into FD. That's where I left it, wondering a bit about how I was going to even dev&test that.

**Comment by knolleary** [comment]
> The PR removes the cookie set by FD,

I do not believe that is the case.

This PR prevents FD adding a second session handler if there is one already there. The FD cookie will still get set using the existing session handler.

**Comment by tve** [comment]
I can't easily test this at the moment, but since it doesn't impact non-FlowForge uses of FD it seems fine to merge it. Thanks for the PR!

**Pull request merged**
